M48
; DRILL file {KiCad (6.0.8)} date Fri Apr 21 14:35:56 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-04-21T14:35:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
%
G90
G05
T2
X120.846Y-63.288
T1
G00X116.446Y-63.538
M15
G01X116.446Y-63.038
M16
G05
T0
M30
